### ISSUE TITLE
Reopening with a clarification request:  Please add that curl to 127.0.0.1 does not work with MK, instead you have to curl to the first IP address shown after issuing the minikube service ... command, so in this example:

### ISSUE THREAD

**Issue by bwolmarans** [f5devcentral/sentence-demo-app#2]
Reopening with a clarification request:  Please add that curl to 127.0.0.1 does not work with MK, instead you have to curl to the first IP address shown after issuing the minikube service ... command, so in this example:

$ kubectl get service -n ingress
NAME                          TYPE       CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE
nginx-ingress-nginx-ingress   NodePort   10.100.80.212   <none>        80:31859/TCP,443:30898/TCP   14m

$ curl -H "Host: api.sentence.com" http://127.0.0.1:31859/api/sentence
curl: (7) Failed to connect to 127.0.0.1 port 31859 after 0 ms: Connection refused

$ minikube service nginx-ingress-nginx-ingress --url -n ingress
http://192.168.49.2:31859
http://192.168.49.2:30898

$ curl -H "Host: api.sentence.com" http://192.168.49.2:31859/api/sentence
{"sentence": {"adjectives": "kind", "animals": "mouse", "colors": "green", "locatio...}

_Originally posted by @bwolmarans in https://github.com/f5devcentral/sentence-demo-app/issues/1#issuecomment-1387381799_

**Comment by MattDierick** [comment]
Done :)
